#!/usr/bin/env bash
# Sandbox AI — one-shot installer
# Usage:  ./install.sh
# Result: a global `sandbox` command that runs the TUI from your local checkout.

set -euo pipefail

# Resolve project root (directory where this script lives)
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_NAME="${SANDBOX_BIN_NAME:-sandbox}"
BIN_DIR="${SANDBOX_BIN_DIR:-$HOME/.local/bin}"
LAUNCHER="$BIN_DIR/$BIN_NAME"

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$*" >&2; }

say "Sandbox AI installer"
say "project: $PROJECT_ROOT"

# 1. bun
if ! command -v bun >/dev/null 2>&1; then
  if [ -x "$HOME/.bun/bin/bun" ]; then
    export PATH="$HOME/.bun/bin:$PATH"
  else
    say "Installing bun (https://bun.sh) ..."
    curl -fsSL https://bun.sh/install | bash
    export PATH="$HOME/.bun/bin:$PATH"
  fi
fi
say "bun: $(bun --version)"

# 2. deps
say "Installing dependencies (this can take a minute on first run) ..."
cd "$PROJECT_ROOT"
bun install

# 3. launcher
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by Sandbox AI install.sh — re-run install.sh to regenerate.
export PATH="\$HOME/.bun/bin:\$PATH"
exec bun run --cwd "$PROJECT_ROOT/packages/opencode" --conditions=browser \
  "$PROJECT_ROOT/packages/opencode/src/index.ts" "\$@"
EOF
chmod +x "$LAUNCHER"
say "launcher installed: $LAUNCHER"

# 4. PATH check
if ! echo ":$PATH:" | grep -q ":$BIN_DIR:"; then
  warn "$BIN_DIR is NOT in your PATH."
  warn "Add this line to your ~/.bashrc (or ~/.zshrc):"
  warn "    export PATH=\"$BIN_DIR:\$PATH\""
  warn "Then run:  source ~/.bashrc"
fi

echo
say "Done. Try:"
echo "  $BIN_NAME auth login --provider sandboxai     # set your API key (https://sandboxai.top)"
echo "  $BIN_NAME                                      # launch TUI"
echo "  $BIN_NAME models | grep sandbox                # verify provider is wired"
echo
say "To uninstall:  rm $LAUNCHER"
